name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Install Haxelib
        run: |
          haxelib install hmm --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib run hmm install --quiet

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Configure Lime for Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build Project.xml android --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/
